USE master

-- create database
IF EXISTS(select * from sys.databases where name='$(DbName)')
BEGIN
	ALTER DATABASE [Basniowa] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE $(DbName)
END

-- recreate database
CREATE DATABASE [$(DbName)]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'$(DbName)', FILENAME = N'$(DbPath)\$(DbName).mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'$(DbName)_log', FILENAME = N'$(DbPath)\$(DbName)_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [$(DbName)] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [$(DbName)] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [$(DbName)] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [$(DbName)] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [$(DbName)] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [$(DbName)] SET ARITHABORT OFF 
GO
ALTER DATABASE [$(DbName)] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [$(DbName)] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [$(DbName)] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [$(DbName)] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [$(DbName)] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [$(DbName)] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [$(DbName)] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [$(DbName)] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [$(DbName)] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [$(DbName)] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [$(DbName)] SET  DISABLE_BROKER 
GO
ALTER DATABASE [$(DbName)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [$(DbName)] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [$(DbName)] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [$(DbName)] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [$(DbName)] SET  READ_WRITE 
GO
ALTER DATABASE [$(DbName)] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [$(DbName)] SET  MULTI_USER 
GO
ALTER DATABASE [$(DbName)] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [$(DbName)] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [$(DbName)] SET DELAYED_DURABILITY = DISABLED 
GO
USE [$(DbName)]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [$(DbName)] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO